package com.io.libraryproject.exception.message;

public class ErrorMessage {

    public final static String BOOK_NOT_FOUND_EXCEPTION = "Book with id : %s not found";
    public final static String RESOURCE_NOT_FOUND_EXCEPTION = "Resource with id %s not found";
    public final static String AUTHOR_NOT_FOUND_EXCEPTION = "Author with id : %s not found";
    public final static String PUBLISHER_NOT_FOUND_EXCEPTION = "Publisher with id : %s not found";
    public final static String CATEGORY_NOT_FOUND_EXCEPTION = "Category with id : %s not found";
    public final static String ROLE_NOT_FOUND_EXCEPTION = "Role with id : %s not found";
    public final static String NOT_PERMITTED_METHOD_MESSAGE = "You don't have any permission to this data";
    public final static String SEQUENCE_CONFLICT_MESSAGE = "This Sequence number is already used.";
    public final static String EMAIL_ALREADY_EXIST_MESSAGE = "Email : %s already exist";
    public final static String JWTTOKEN_ERROR_MESSAGE = "JWT Token Validation Error : %s";
    public final static String PRINCIPAL_FOUND_MESSAGE = "User not found";
    public final static String USER_NOT_FOUND_EXCEPTION = "User with id : %s not found";
    public final static String PASSWORD_NOT_MATCHED_MESSAGE = "Your passwords are not matched";
    public final static String ISBN_ALREADY_EXIST_MESSAGE = "ISBN : %s already exist";
}
